### PR TITLE
Adjust introductory section and add invactive time

### PR DESCRIPTION
**Pull request by centic9**
The tool is not only about sidetone any more, so add a more general introduction

### CODE REVIEW

**Comment by Sapd** [comment]
Yeah the text was a bit dated.
Grammerly says, that some commas are missing in your suggestion:

> A tool to control certain aspects of USB-connected headsets on Linux. Currently, support is provided for adjusting sidetone, getting battery state, controlling LEDs, and setting the inactive time. See below for which headset supports which feature.

**Comment by centic9** [comment]
Sorry, I don't use that service and do not want to install it. Also I am not a native speaker, so not sure which ones exactly you are missing here? :)

**Comment by Sapd** [comment]
It's an online service with AI. But I wasn't sure bc I'm not native speaker; I quoted the corrected version above, here again:

> A tool to control certain aspects of USB-connected headsets on Linux. Currently, support is provided for adjusting sidetone, getting battery state, controlling LEDs, and setting the inactive time. See below for which headset supports which feature.

(But it's not really important, I just waited for your opinion)

**Comment by centic9** [comment]
Ah, ok, didn't notice that, I updated the branch now.

**Pull request merged**
