### PR TITLE
Added a switch for short output: -c

### PR DESCRIPTION
**Pull request by Hades0299**
For usage in scripts I do not want to parse the output and filter out
the usefull infomration or clutter the line with redirects to /dev/null.
Therefore I added a option, that removes every output, except whith the
-b-switch, where the battery-percentage (or -1 for loading) are printed.

While doing so, the default changed a bit:
Only when the -h-swich is present, we output name and author of this
programm.

Further: my Texteditor removed some whitespaces in empty lines....

### CODE REVIEW

**Comment by Sapd** [comment]
Looks good so far. Any reason the PRINT macro doesn't call printf directly?

**Comment by Hades0299** [comment]
The only reason the macro does not call printf is, that i wrote this while i was quite tired, and couldn't figure out how to pass multiple arguments through a macro to printf. I can try to figure that out, but if you have an Idea, I'm all ears ;)

**Comment by Sapd** [comment]
Macros support variadic arguments https://stackoverflow.com/questions/20639632/how-to-wrap-printf-into-a-function-or-macro

**Comment by Hades0299** [comment]
Seems that my abilities to use google need updating.....

**Comment by Sapd** [comment]
Looks good, thanks for your contribution.

**Pull request merged**
