### PR TITLE
SteelSeries Arctis 7 Battery Support + 2019 Model Support

### PR DESCRIPTION
**Pull request by jamesj999**
Added battery support and support for 2019 variant of SteelSeries Arctis 7.

### CODE REVIEW

**Comment by jamesj999** [comment]
Fixes https://github.com/Sapd/HeadsetControl/issues/35

**Comment by Sapd** [comment]
Thank you!
Is the Request still Work-In-Progress? (As some commits were added some hours ago).
Also the README needs an update, I can also take care of it, though.

**Comment by jamesj999** [comment]
Hello there!

Apologies, we were slightly premature with the request - we spotted a couple of issues and fixed them. We're just double checking the fully charged value as I've seen it go over 100% so we're verifying on a second headset and will cap it at 100% if necessary. I'll update the readme now and will let you know when we've checked the battery percentage issue.

Thanks,
James

**Comment by raiscan** [comment]
> Thank you!
Thank you! We had a good basis to get our headset battery in Linux thanks to this project.

**Comment by raiscan** [comment]
After experimenting, I believe their battery percentage response isn't calibrated very well or calibrated to a reference battery; mine never goes above 99, while @jamesj999 's can reach all the way to 116 before capping out. The SteelSeries UI in Windows uses a simple battery segment indicator so I imagine they're aware it's not particularly accurate.

When I get home tonight I'll just limit the max output to 100. It'll be good enough for anyone's purposes; especially since unplugging James's heatset immediately drops it lower than 100 :)

**Comment by Sapd** [comment]
Yes I think this is not uncommon, there are two ways to measure how full a battery is.

The first (halfway accurate) method is to empty the battery completely and charge it until the maximum voltage is reached and count the watt-hours. (Now you can simply integrate the watt-hours while using the headset and know how much of the maximum number is left).

The second method (probably with most headsets) is to simply measure the voltage. It's very inaccurate and not really linear. Therefore, it may well be that the value is also inaccurate.

**Comment by raiscan** [comment]
Hello! I forgot last night. I've made some changes to the arctis 7 rules due to the old udev rules not working (See commits 669aac0 & 2128b78). I have also capped the battery readout on 100% to both arctis 7 and arctis 7 2019 as they seem to be pretty darn similar and we've seen it on one at least.

Please let me know if there's anything you'd like us to change, but otherwise I think we're done :) Thanks!

**Comment by Sapd** [comment]
Looks good, maybe the UDEV rules need to be adjusted for other devices, but this pull request is fine.

**Pull request merged**
