### PR TITLE
adds support for SteelSeries Arctis Nova 7

### PR DESCRIPTION
**Pull request by mbackermann**
Adds support for the new SteelSeries Arctis Nova 7 and Arctis Nova 7x Headset

### CODE REVIEW

**Comment by eslin** [comment]
I tested this with my SteelSeries Arctis Nova 7x, it turns out that has another ID.
This is a diff adding support for that.
As for testing I was only able to test the battery and it seems to work (they was 100% all the time, but they were fresh of the charger).

```
diff --git a/src/devices/steelseries_arctis_nova_7.c b/src/devices/steelseries_arctis_nova_7.c
index b193ab1..2f0ad41 100644
--- a/src/devices/steelseries_arctis_nova_7.c
+++ b/src/devices/steelseries_arctis_nova_7.c
@@ -11,13 +11,14 @@
 static struct device device_arctis;
 
 #define ID_ARCTIS_NOVA_7     0x2202
+#define ID_ARCTIS_NOVA_7x     0x2206
 
 #define BATTERY_MAX 0x04
 #define BATTERY_MIN 0x00
 
 #define HEADSET_OFFLINE 0x01
 
-static const uint16_t PRODUCT_IDS[] = { ID_ARCTIS_NOVA_7 };
+static const uint16_t PRODUCT_IDS[] = { ID_ARCTIS_NOVA_7, ID_ARCTIS_NOVA_7x };
 
 static int arctis_nova_7_send_sidetone(hid_device* device_handle, uint8_t num);
 static int arctis_nova_7_send_inactive_time(hid_device* device_handle, uint8_t num);

```

**Comment by mbackermann** [comment]
Thanks for sharing it @eslin. I added the support for the 7x

**Comment by Eruvae** [comment]
I added support to read out the Chat-Mix dial. You can find the commit [here](https://github.com/Eruvae/HeadsetControl/commit/4ee8620b8165fca672fb26821885e4427f204313). If you want you can add it to this pull request, or I can create a separate pull request when this is merged.

**Comment by mbackermann** [comment]
@Eruvae Thanks for contributing! I added the support to my PR

**Comment by Calosis** [comment]
Artics Nova 7P is missing aswell. Device ID: 0x220a

Tested working on my system.

**Comment by mbackermann** [comment]
@Calosis thanks! Just added the support

**Pull request merged**
