### PR TITLE
adds sidetone support for Logitech G Pro X Wireless

### PR DESCRIPTION
**Pull request by thoraxe**

### CODE REVIEW

**Comment by Sapd** [comment]
I noticed that the packet is the same like in logitech_gpro.c

you can just add the ID of your headset to the existing implementation (see into the .c file of Corsair void for an example) in logitech_gpro.c

**Comment by thoraxe** [comment]
@Sapd 10-4, I will work on that.

Do you have any interest in me trying to figure out other things like battery level, surround sound settings, etc?

**Comment by Sapd** [comment]
Feel free to ask any questions, but make sure to take a look here, there is a full tutorial: https://github.com/Sapd/HeadsetControl/wiki/Development

**Comment by thoraxe** [comment]
Updated PR by combining Pro and Pro X into a single file as requested, removed prox files.

I'll ask the questions about battery, etc. via an issue.

**Pull request merged**
